In [16]:
import numpy as np

matrice = []
num = 5

for i in range(0,num) :
    A = np.random.randint(10, size=num)
    matrice.append(list(A))


print(matrice)
 

[[6, 4, 0, 1, 2], [7, 3, 3, 6, 2], [8, 5, 0, 5, 4], [0, 3, 6, 5, 2], [0, 5, 5, 2, 3]]


In [1]:
import numpy as np

def matricegenerator(num_V , num_w_min , num_w_max):
    matrice = []   
    for i in range(0,num_V) :
        A = np.random.randint(num_w_min , num_w_max , size=(num_V))
        print(A)
        matrice.append(list(A))
    return matrice

matricegenerator(10,0,2)
#matricegenerator(5 , 0 , 2 )
# f = open("matrice_random.txt", "a")
# f.write(str(matricegenerator(30 , 0 , 50)))
# f.close()


[0 0 1 0 1 0 0 0 0 0]
[0 0 1 0 1 0 0 1 0 0]
[0 0 0 0 1 1 1 0 1 0]
[0 0 0 1 0 1 0 1 0 1]
[1 0 1 1 0 1 0 0 0 0]
[1 1 1 0 1 1 1 1 1 0]
[1 0 1 0 0 1 1 0 0 1]
[1 1 1 1 0 1 0 1 0 0]
[1 1 1 1 1 1 1 0 0 0]
[1 0 0 0 1 0 1 1 1 0]


[[0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1, 1, 1, 0, 1, 0],
 [0, 0, 0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 1, 0, 1, 0, 0, 0, 0],
 [1, 1, 1, 0, 1, 1, 1, 1, 1, 0],
 [1, 0, 1, 0, 0, 1, 1, 0, 0, 1],
 [1, 1, 1, 1, 0, 1, 0, 1, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
 [1, 0, 0, 0, 1, 0, 1, 1, 1, 0]]

In [4]:
import itertools
import copy
import networkx as nx
import pandas as pd
import matplotlib.pyplot as plt

# node == vertex == point
# edge == arc == link
edgelist = pd.read_csv('https://gist.githubusercontent.com/brooksandrew/e570c38bcc72a8d102422f2af836513b/raw/89c76b2563dbc0e88384719a35cba0dfc04cd522/edgelist_sleeping_giant.csv')
edgelist.head(10)

node1         node2 trail  distance color  estimate
0  rs_end_north          v_rs    rs      0.30   red         0
1          v_rs          b_rs    rs      0.21   red         0
2          b_rs          g_rs    rs      0.11   red         0
3          g_rs          w_rs    rs      0.18   red         0
4          w_rs          o_rs    rs      0.21   red         0
5          o_rs          y_rs    rs      0.12   red         0
6          y_rs  rs_end_south    rs      0.39   red         0
7  rc_end_north          v_rc    rc      0.70   red         0
8          v_rc          b_rc    rc      0.04   red         0
9          b_rc          g_rc    rc      0.15   red         0

In [ ]:
# import random

# # to generate random names to nodes 
# import names

# # nombre des clients
# client_count = random.randint(8, 22) 

# # nombre de vehicule
# vehicule_count = random.randint(3 , 6)

# # nombre de checkpoints
# nodes_count = random.randint(10, 30)

# # depot lat , lng
# lat_depot = '{:.6f}'.format(random.uniform(20,30)) 
# lng_depot = '{:.6f}'.format(random.uniform(20,30))
 

# # localisation des checkpoints 

# # distance entre les viles 

# # trafic routier 

# # estimation trajet

# class Nodes:
#     def __init__(self , key , lat , lng , tag):
#         self.key = key 
#         self.lat = lat 
#         self.lng = lng 
#         self.tag = tag


# # fonction qui genere un tableau de checkpoint avec leur positions 
# def generate_node (key , lat , lng , tag):
#     node = Nodes(key , lat , lng , tag)
#     return node
    
# def generate_nodes_list (max_nodes , min_lat , max_lat , min_lng , max_lng) :
#     nodes = []
#     for i in range(0,max_nodes) :
#         lat='{:.6f}'.format(random.uniform(min_lat,max_lat)) 
#         lng='{:.6f}'.format(random.uniform(min_lng,max_lng))
#         tag=names.get_last_name()
#         node_obj = generate_node(i , lat , lng , tag)
#         nodes.append(node_obj)
#     return nodes

 
# nodes_list = generate_nodes_list(10, 20, 25, 10, 25)

# for i in range(0 , len(nodes_list)) : 
#     print(  "id : ", nodes_list[i].key , "lat : " , nodes_list[i].lat , "lng : " , nodes_list[i].lng , "tag : ",nodes_list[i].tag)